# configuration vars for scripts

# medicare supplement ojbect ids from hubspot
hs_object_types = {
    'msp': "2-8483761",
    'pdp': "2-8567541",
    'map': "2-7775359",
    'copay': "2-8483892",
    'dvh': "2-8483915"
}

agents = [
 ('Aaron', 'Butler', 'aaron.butler@medicareschool.com'),
 ('Adrian', 'Hardin', 'adrian.hardin@medicareschool.com'),
 ('Brian', 'Schwartz', 'brian.schwartz@medicareschool.com'),
 ('Carie', 'Wright', 'carie.wright@medicareschool.com'),
 ('Cory', 'Caldwell', 'cory.caldwell@medicareschool.com'),
 ('Darrin', 'Neal', 'darrin.neal@medicareschool.com'),
 ('David', 'Strehlow', 'david.strehlow@medicareschool.com'),
 ('EnlightNU', 'Legacy', 'legacy.enlightnu.noemail@medicareschool.com'),
 ('EnlightNuUsaLLC', 'House', 'house.enlightnu.noemail@medicareschool.com'),
 ('Gabriel', 'Rhone', 'gabriel.rhone@medicareschool.com'),
 ('Garrett', 'McKinzie', 'garrett.mckinzie@medicareschool.com'),
 ('Howard', 'Seigle', 'howard.seigle@medicareschool.com'),
 ('Jordan', 'Otte', 'jordan.otte@medicareschool.com'),
 ('Jordan', 'Seifert', 'jordan.seifert@medicareschool.com'),
 ('Josh', 'Musick', 'josh.musick@medicareschool.com'),
 ('Justin', 'Cohen', 'justin.cohen@medicareschool.com'),
 ('Ken', 'Tomberlin', 'ken.tomberlin@medicareschool.com'),
 ('Latesa', 'Pasley', 'latesa.pasley@medicareschool.com'),
 ('Mark', 'Abkemeier', 'mark.abkemeier@medicareschool.com'),
 ('Mark', 'Files', 'mark.files@medicareschool.com'),
 ('Marvin', 'Musick', 'marvin.musick@medicareschool.com'),
 ('Matthew', 'Cano', 'matthew.cano@medicareschool.com'),
 ('Matthew', 'Duffey', 'matthew.duffey@medicareschool.com'),
 ('Nick', 'Oberle', 'nick.oberle@medicareschool.com'),
 ('Nick', 'Thompson', 'nick.thompson@medicareschool.com'),
 ('Patrick', 'Stang', 'patrick.stang@medicareschool.com'),
 ('Pete', 'Scalzo', 'pete.scalzo@medicareschool.com'),
 ('Rebecca', 'Sublette', 'rebecca.sublette@medicareschool.com'),
 ('Rhee', 'Cano', 'rhee.cano@medicareschool.com'),
 ('Rhi', 'Neal', 'rhi.neal@medicareschool.com'),
 ('Stephanie', 'Kiely', 'stephanie.kiely@medicareschool.com'),
 ('Steve', 'Brooks', 'steve.brooks@medicareschool.com'),
]

agents = {
    'aaron.butler@medicareschool.com': {'firstname': 'Aaron',
                                     'lastname': 'Butler'},
    'adrian.hardin@medicareschool.com': {'firstname': 'Adrian',
                                      'lastname': 'Hardin'},
    'brian.schwartz@medicareschool.com': {'firstname': 'Brian',
                                       'lastname': 'Schwartz'},
    'carie.wright@medicareschool.com': {'firstname': 'Carie',
                                        'lastname': 'Wright'},
    'cory.caldwell@medicareschool.com': {'firstname': 'Cory',
                                         'lastname': 'Caldwell'},
    'darrin.neal@medicareschool.com': {'firstname': 'Darrin', 'lastname': 'Neal'},
    'david.strehlow@medicareschool.com': {'firstname': 'David',
                                          'lastname': 'Strehlow'},
    'gabriel.rhone@medicareschool.com': {'firstname': 'Gabriel',
                                         'lastname': 'Rhone'},
    'garrett.mckinzie@medicareschool.com': {'firstname': 'Garrett',
                                            'lastname': 'McKinzie'},
    'house.enlightnu.noemail@medicareschool.com': {'firstname': 'EnlightNuUsaLLC',
                                                   'lastname': 'House'},
    'howard.seigle@medicareschool.com': {'firstname': 'Howard',
                                         'lastname': 'Seigle'},
    'jordan.otte@medicareschool.com': {'firstname': 'Jordan', 'lastname': 'Otte'},
    'jordan.seifert@medicareschool.com': {'firstname': 'Jordan',
                                          'lastname': 'Seifert'},
    'josh.musick@medicareschool.com': {'firstname': 'Josh', 'lastname': 'Musick'},
    'justin.cohen@medicareschool.com': {'firstname': 'Justin',
                                        'lastname': 'Cohen'},
    'ken.tomberlin@medicareschool.com': {'firstname': 'Ken',
                                         'lastname': 'Tomberlin'},
    'latesa.pasley@medicareschool.com': {'firstname': 'Latesa',
                                         'lastname': 'Pasley'},
    'legacy.enlightnu.noemail@medicareschool.com': {'firstname': 'EnlightNU',
                                                    'lastname': 'Legacy'},
    'mark.abkemeier@medicareschool.com': {'firstname': 'Mark',
                                          'lastname': 'Abkemeier'},
    'mark.files@medicareschool.com': {'firstname': 'Mark', 'lastname': 'Files'},
    'marvin.musick@medicareschool.com': {'firstname': 'Marvin',
                                         'lastname': 'Musick'},
    'matthew.cano@medicareschool.com': {'firstname': 'Matthew',
                                        'lastname': 'Cano'},
    'matthew.duffey@medicareschool.com': {'firstname': 'Matthew',
                                          'lastname': 'Duffey'},
    'nick.oberle@medicareschool.com': {'firstname': 'Nick', 'lastname': 'Oberle'},
    'nick.thompson@medicareschool.com': {'firstname': 'Nick',
                                         'lastname': 'Thompson'},
    'patrick.stang@medicareschool.com': {'firstname': 'Patrick',
                                         'lastname': 'Stang'},
    'pete.scalzo@medicareschool.com': {'firstname': 'Pete', 'lastname': 'Scalzo'},
    'rebecca.sublette@medicareschool.com': {'firstname': 'Rebecca',
                                            'lastname': 'Sublette'},
    'rhee.cano@medicareschool.com': {'firstname': 'Rhee', 'lastname': 'Cano'},
    'rhi.neal@medicareschool.com': {'firstname': 'Rhi', 'lastname': 'Neal'},
    'stephanie.kiely@medicareschool.com': {'firstname': 'Stephanie',
                                           'lastname': 'Kiely'},
    'steve.brooks@medicareschool.com': {'firstname': 'Steve',
                                        'lastname': 'Brooks'}
}
